[2022-02-15 02:28:53,132] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.fct_orders manual__2022-02-15T02:27:57.149490+00:00 [queued]>
[2022-02-15 02:28:53,165] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.fct_orders manual__2022-02-15T02:27:57.149490+00:00 [queued]>
[2022-02-15 02:28:53,166] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 02:28:53,168] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 02:28:53,169] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 02:28:53,199] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): model.my_new_project.fct_orders> on 2022-02-15 02:27:57.149490+00:00
[2022-02-15 02:28:53,206] {standard_task_runner.py:52} INFO - Started process 796 to run task
[2022-02-15 02:28:53,220] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'model.my_new_project.fct_orders', 'manual__2022-02-15T02:27:57.149490+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmp5u_eviyk', '--error-file', '/tmp/tmp7rxzlpem']
[2022-02-15 02:28:53,223] {standard_task_runner.py:77} INFO - Job 72: Subtask model.my_new_project.fct_orders
[2022-02-15 02:28:53,347] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.model.my_new_project.fct_orders manual__2022-02-15T02:27:57.149490+00:00 [running]> on host de7a240d0d46
[2022-02-15 02:28:53,528] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=model.my_new_project.fct_orders
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T02:27:57.149490+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T02:27:57.149490+00:00
[2022-02-15 02:28:53,531] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 02:28:53,533] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json run --target dev --models fct_orders             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 02:28:53,611] {subprocess.py:85} INFO - Output:
[2022-02-15 02:29:07,186] {subprocess.py:89} INFO - 02:29:07  Running with dbt=1.0.1
[2022-02-15 02:29:07,535] {subprocess.py:89} INFO - 02:29:07  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-02-15 02:29:07,535] {subprocess.py:89} INFO - There are 2 unused configuration paths:
[2022-02-15 02:29:07,536] {subprocess.py:89} INFO - - models.jaffle_shop.staging
[2022-02-15 02:29:07,537] {subprocess.py:89} INFO - - models.jaffle_shop.marts.core
[2022-02-15 02:29:07,538] {subprocess.py:89} INFO - 
[2022-02-15 02:29:07,567] {subprocess.py:89} INFO - 02:29:07  Found 7 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 02:29:07,574] {subprocess.py:89} INFO - 02:29:07
[2022-02-15 02:29:12,863] {subprocess.py:89} INFO - 02:29:12  Concurrency: 4 threads (target='dev')
[2022-02-15 02:29:12,871] {subprocess.py:89} INFO - 02:29:12
[2022-02-15 02:29:13,020] {subprocess.py:89} INFO - 02:29:13  1 of 1 START view model dbt_bytecode_training.fct_orders........................ [RUN]
[2022-02-15 02:29:15,371] {subprocess.py:89} INFO - 02:29:15  1 of 1 OK created view model dbt_bytecode_training.fct_orders................... [SUCCESS 1 in 2.35s]
[2022-02-15 02:29:15,452] {subprocess.py:89} INFO - 02:29:15
[2022-02-15 02:29:15,455] {subprocess.py:89} INFO - 02:29:15  Finished running 1 view model in 7.87s.
[2022-02-15 02:29:15,465] {subprocess.py:89} INFO - 02:29:15
[2022-02-15 02:29:15,470] {subprocess.py:89} INFO - 02:29:15  Completed successfully
[2022-02-15 02:29:15,474] {subprocess.py:89} INFO - 02:29:15
[2022-02-15 02:29:15,479] {subprocess.py:89} INFO - 02:29:15  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-02-15 02:29:16,063] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 02:29:16,109] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=model.my_new_project.fct_orders, execution_date=20220215T022757, start_date=20220215T022853, end_date=20220215T022916
[2022-02-15 02:29:16,175] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 02:29:16,234] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
