[2022-02-15 03:25:00,531] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:00,568] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:00,570] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:00,571] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 03:25:00,572] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:00,591] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): model.my_new_project.int_orders_pivoted> on 2022-02-15 03:24:14.594120+00:00
[2022-02-15 03:25:00,596] {standard_task_runner.py:52} INFO - Started process 2098 to run task
[2022-02-15 03:25:00,614] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'model.my_new_project.int_orders_pivoted', 'manual__2022-02-15T03:24:14.594120+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmpylg69ilz', '--error-file', '/tmp/tmp5424l9z5']
[2022-02-15 03:25:00,625] {standard_task_runner.py:77} INFO - Job 131: Subtask model.my_new_project.int_orders_pivoted
[2022-02-15 03:25:00,780] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:24:14.594120+00:00 [running]> on host 459d09dd7c86
[2022-02-15 03:25:00,909] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=model.my_new_project.int_orders_pivoted
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T03:24:14.594120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T03:24:14.594120+00:00
[2022-02-15 03:25:00,913] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 03:25:00,917] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json run --target dev --models int_orders_pivoted             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 03:25:00,942] {subprocess.py:85} INFO - Output:
[2022-02-15 03:25:10,197] {subprocess.py:89} INFO - 03:25:10  Running with dbt=1.0.1
[2022-02-15 03:25:10,690] {subprocess.py:89} INFO - 03:25:10  Found 8 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 03:25:10,702] {subprocess.py:89} INFO - 03:25:10
[2022-02-15 03:25:14,386] {subprocess.py:89} INFO - 03:25:14  Concurrency: 4 threads (target='dev')
[2022-02-15 03:25:14,391] {subprocess.py:89} INFO - 03:25:14
[2022-02-15 03:25:14,471] {subprocess.py:89} INFO - 03:25:14  1 of 1 START table model dbt_bytecode_training.int_orders_pivoted............... [RUN]
[2022-02-15 03:25:18,973] {subprocess.py:89} INFO - 03:25:18  1 of 1 OK created table model dbt_bytecode_training.int_orders_pivoted.......... [SUCCESS 1 in 4.49s]
[2022-02-15 03:25:19,087] {subprocess.py:89} INFO - 03:25:19
[2022-02-15 03:25:19,091] {subprocess.py:89} INFO - 03:25:19  Finished running 1 table model in 8.38s.
[2022-02-15 03:25:19,099] {subprocess.py:89} INFO - 03:25:19
[2022-02-15 03:25:19,104] {subprocess.py:89} INFO - 03:25:19  Completed successfully
[2022-02-15 03:25:19,108] {subprocess.py:89} INFO - 03:25:19
[2022-02-15 03:25:19,112] {subprocess.py:89} INFO - 03:25:19  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-02-15 03:25:19,715] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 03:25:19,794] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=model.my_new_project.int_orders_pivoted, execution_date=20220215T032414, start_date=20220215T032500, end_date=20220215T032519
[2022-02-15 03:25:19,868] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 03:25:19,922] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
