[2022-02-15 03:15:02,781] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:14:06.780838+00:00 [queued]>
[2022-02-15 03:15:02,816] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:14:06.780838+00:00 [queued]>
[2022-02-15 03:15:02,817] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:15:02,818] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 03:15:02,821] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:15:02,859] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): model.my_new_project.int_orders_pivoted> on 2022-02-15 03:14:06.780838+00:00
[2022-02-15 03:15:02,888] {standard_task_runner.py:52} INFO - Started process 1291 to run task
[2022-02-15 03:15:02,905] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'model.my_new_project.int_orders_pivoted', 'manual__2022-02-15T03:14:06.780838+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmpdyrchsfx', '--error-file', '/tmp/tmpwsp6p107']
[2022-02-15 03:15:02,907] {standard_task_runner.py:77} INFO - Job 114: Subtask model.my_new_project.int_orders_pivoted
[2022-02-15 03:15:03,076] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:14:06.780838+00:00 [running]> on host 459d09dd7c86
[2022-02-15 03:15:03,269] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=model.my_new_project.int_orders_pivoted
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T03:14:06.780838+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T03:14:06.780838+00:00
[2022-02-15 03:15:03,276] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 03:15:03,288] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json run --target dev --models int_orders_pivoted             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 03:15:03,375] {subprocess.py:85} INFO - Output:
[2022-02-15 03:15:15,473] {subprocess.py:89} INFO - 03:15:15  Running with dbt=1.0.1
[2022-02-15 03:15:16,133] {subprocess.py:89} INFO - 03:15:16  Found 8 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 03:15:16,140] {subprocess.py:89} INFO - 03:15:16
[2022-02-15 03:15:20,566] {subprocess.py:89} INFO - 03:15:20  Concurrency: 4 threads (target='dev')
[2022-02-15 03:15:20,569] {subprocess.py:89} INFO - 03:15:20
[2022-02-15 03:15:20,611] {subprocess.py:89} INFO - 03:15:20  1 of 1 START table model dbt_bytecode_training.int_orders_pivoted............... [RUN]
[2022-02-15 03:15:23,928] {subprocess.py:89} INFO - 03:15:23  1 of 1 OK created table model dbt_bytecode_training.int_orders_pivoted.......... [SUCCESS 1 in 3.31s]
[2022-02-15 03:15:23,988] {subprocess.py:89} INFO - 03:15:23
[2022-02-15 03:15:23,992] {subprocess.py:89} INFO - 03:15:23  Finished running 1 table model in 7.84s.
[2022-02-15 03:15:24,010] {subprocess.py:89} INFO - 03:15:24
[2022-02-15 03:15:24,013] {subprocess.py:89} INFO - 03:15:24  Completed successfully
[2022-02-15 03:15:24,019] {subprocess.py:89} INFO - 03:15:24
[2022-02-15 03:15:24,024] {subprocess.py:89} INFO - 03:15:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-02-15 03:15:24,423] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 03:15:24,455] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=model.my_new_project.int_orders_pivoted, execution_date=20220215T031406, start_date=20220215T031502, end_date=20220215T031524
[2022-02-15 03:15:24,523] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 03:15:24,566] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
