[2022-02-15 03:25:21,182] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.test.my_new_project.int_orders_pivoted manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:21,229] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.test.my_new_project.int_orders_pivoted manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:21,250] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:21,251] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 03:25:21,252] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:21,284] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): test.my_new_project.int_orders_pivoted> on 2022-02-15 03:24:14.594120+00:00
[2022-02-15 03:25:21,292] {standard_task_runner.py:52} INFO - Started process 2216 to run task
[2022-02-15 03:25:21,314] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'test.my_new_project.int_orders_pivoted', 'manual__2022-02-15T03:24:14.594120+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmpmjpsh6mp', '--error-file', '/tmp/tmp1zdq1rce']
[2022-02-15 03:25:21,316] {standard_task_runner.py:77} INFO - Job 133: Subtask test.my_new_project.int_orders_pivoted
[2022-02-15 03:25:21,506] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.test.my_new_project.int_orders_pivoted manual__2022-02-15T03:24:14.594120+00:00 [running]> on host 459d09dd7c86
[2022-02-15 03:25:21,694] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=test.my_new_project.int_orders_pivoted
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T03:24:14.594120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T03:24:14.594120+00:00
[2022-02-15 03:25:21,698] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 03:25:21,700] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json test --target dev --models int_orders_pivoted             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 03:25:21,725] {subprocess.py:85} INFO - Output:
[2022-02-15 03:25:28,634] {subprocess.py:89} INFO - 03:25:28  Running with dbt=1.0.1
[2022-02-15 03:25:29,018] {subprocess.py:89} INFO - 03:25:29  Found 8 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 03:25:29,022] {subprocess.py:89} INFO - 03:25:29
[2022-02-15 03:25:29,025] {subprocess.py:89} INFO - 03:25:29  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-02-15 03:25:29,666] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 03:25:29,736] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=test.my_new_project.int_orders_pivoted, execution_date=20220215T032414, start_date=20220215T032521, end_date=20220215T032529
[2022-02-15 03:25:29,808] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 03:25:29,852] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
