[2022-02-15 02:28:13,201] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.dbt_seed manual__2022-02-15T02:27:57.149490+00:00 [queued]>
[2022-02-15 02:28:13,242] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.dbt_seed manual__2022-02-15T02:27:57.149490+00:00 [queued]>
[2022-02-15 02:28:13,244] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 02:28:13,247] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 02:28:13,249] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 02:28:13,303] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): dbt_seed> on 2022-02-15 02:27:57.149490+00:00
[2022-02-15 02:28:13,320] {standard_task_runner.py:52} INFO - Started process 651 to run task
[2022-02-15 02:28:13,330] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'dbt_seed', 'manual__2022-02-15T02:27:57.149490+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmpovd9z2rq', '--error-file', '/tmp/tmppjha2730']
[2022-02-15 02:28:13,332] {standard_task_runner.py:77} INFO - Job 66: Subtask dbt_seed
[2022-02-15 02:28:13,432] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.dbt_seed manual__2022-02-15T02:27:57.149490+00:00 [running]> on host de7a240d0d46
[2022-02-15 02:28:13,511] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=dbt_seed
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T02:27:57.149490+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T02:27:57.149490+00:00
[2022-02-15 02:28:13,514] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 02:28:13,517] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt seed --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1']
[2022-02-15 02:28:13,537] {subprocess.py:85} INFO - Output:
[2022-02-15 02:28:19,365] {subprocess.py:89} INFO - 02:28:19  Running with dbt=1.0.1
[2022-02-15 02:28:19,463] {subprocess.py:89} INFO - 02:28:19  Unable to do partial parsing because config vars, config profile, or config target have changed
[2022-02-15 02:28:22,987] {subprocess.py:89} INFO - 02:28:22  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-02-15 02:28:22,988] {subprocess.py:89} INFO - There are 2 unused configuration paths:
[2022-02-15 02:28:22,989] {subprocess.py:89} INFO - - models.jaffle_shop.staging
[2022-02-15 02:28:22,990] {subprocess.py:89} INFO - - models.jaffle_shop.marts.core
[2022-02-15 02:28:22,991] {subprocess.py:89} INFO - 
[2022-02-15 02:28:23,064] {subprocess.py:89} INFO - 02:28:23  Found 7 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 02:28:23,072] {subprocess.py:89} INFO - 02:28:23
[2022-02-15 02:28:27,358] {subprocess.py:89} INFO - 02:28:27  Concurrency: 4 threads (target='dev')
[2022-02-15 02:28:27,361] {subprocess.py:89} INFO - 02:28:27
[2022-02-15 02:28:27,376] {subprocess.py:89} INFO - 02:28:27  1 of 1 START seed file dbt_bytecode_training.employees.......................... [RUN]
[2022-02-15 02:28:32,547] {subprocess.py:89} INFO - 02:28:32  1 of 1 OK loaded seed file dbt_bytecode_training.employees...................... [INSERT 4 in 5.17s]
[2022-02-15 02:28:32,623] {subprocess.py:89} INFO - 02:28:32
[2022-02-15 02:28:32,627] {subprocess.py:89} INFO - 02:28:32  Finished running 1 seed in 9.55s.
[2022-02-15 02:28:32,696] {subprocess.py:89} INFO - 02:28:32
[2022-02-15 02:28:32,700] {subprocess.py:89} INFO - 02:28:32  Completed successfully
[2022-02-15 02:28:32,707] {subprocess.py:89} INFO - 02:28:32
[2022-02-15 02:28:32,711] {subprocess.py:89} INFO - 02:28:32  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-02-15 02:28:33,752] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 02:28:33,884] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=dbt_seed, execution_date=20220215T022757, start_date=20220215T022813, end_date=20220215T022833
[2022-02-15 02:28:34,027] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 02:28:34,315] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
