[2022-02-15 03:05:49,353] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:04:57.520087+00:00 [queued]>
[2022-02-15 03:05:49,369] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:04:57.520087+00:00 [queued]>
[2022-02-15 03:05:49,370] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:05:49,371] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 03:05:49,372] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:05:49,392] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): model.my_new_project.int_orders_pivoted> on 2022-02-15 03:04:57.520087+00:00
[2022-02-15 03:05:49,401] {standard_task_runner.py:52} INFO - Started process 546 to run task
[2022-02-15 03:05:49,418] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'model.my_new_project.int_orders_pivoted', 'manual__2022-02-15T03:04:57.520087+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmpjof2pjm3', '--error-file', '/tmp/tmpg_vdr9wb']
[2022-02-15 03:05:49,421] {standard_task_runner.py:77} INFO - Job 97: Subtask model.my_new_project.int_orders_pivoted
[2022-02-15 03:05:49,577] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.model.my_new_project.int_orders_pivoted manual__2022-02-15T03:04:57.520087+00:00 [running]> on host 459d09dd7c86
[2022-02-15 03:05:49,696] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=model.my_new_project.int_orders_pivoted
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T03:04:57.520087+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T03:04:57.520087+00:00
[2022-02-15 03:05:49,698] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 03:05:49,701] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json run --target dev --models int_orders_pivoted             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 03:05:49,731] {subprocess.py:85} INFO - Output:
[2022-02-15 03:06:00,166] {subprocess.py:89} INFO - 03:06:00  Running with dbt=1.0.1
[2022-02-15 03:06:00,533] {subprocess.py:89} INFO - 03:06:00  Found 8 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 03:06:00,544] {subprocess.py:89} INFO - 03:06:00
[2022-02-15 03:06:06,066] {subprocess.py:89} INFO - 03:06:06  Concurrency: 4 threads (target='dev')
[2022-02-15 03:06:06,069] {subprocess.py:89} INFO - 03:06:06
[2022-02-15 03:06:06,095] {subprocess.py:89} INFO - 03:06:06  1 of 1 START table model dbt_bytecode_training.int_orders_pivoted............... [RUN]
[2022-02-15 03:06:09,740] {subprocess.py:89} INFO - 03:06:09  1 of 1 OK created table model dbt_bytecode_training.int_orders_pivoted.......... [SUCCESS 1 in 3.64s]
[2022-02-15 03:06:09,826] {subprocess.py:89} INFO - 03:06:09
[2022-02-15 03:06:09,828] {subprocess.py:89} INFO - 03:06:09  Finished running 1 table model in 9.28s.
[2022-02-15 03:06:09,835] {subprocess.py:89} INFO - 03:06:09
[2022-02-15 03:06:09,835] {subprocess.py:89} INFO - 03:06:09  Completed successfully
[2022-02-15 03:06:09,837] {subprocess.py:89} INFO - 03:06:09
[2022-02-15 03:06:09,839] {subprocess.py:89} INFO - 03:06:09  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-02-15 03:06:10,218] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 03:06:10,253] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=model.my_new_project.int_orders_pivoted, execution_date=20220215T030457, start_date=20220215T030549, end_date=20220215T030610
[2022-02-15 03:06:10,293] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 03:06:10,336] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
