[2022-02-15 03:25:21,828] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.test.my_new_project.fct_orders manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:21,875] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.test.my_new_project.fct_orders manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:21,876] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:21,877] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 03:25:21,879] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:21,906] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): test.my_new_project.fct_orders> on 2022-02-15 03:24:14.594120+00:00
[2022-02-15 03:25:21,914] {standard_task_runner.py:52} INFO - Started process 2219 to run task
[2022-02-15 03:25:21,927] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'test.my_new_project.fct_orders', 'manual__2022-02-15T03:24:14.594120+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmpy8fmf1nw', '--error-file', '/tmp/tmpp_a8p4hy']
[2022-02-15 03:25:21,928] {standard_task_runner.py:77} INFO - Job 134: Subtask test.my_new_project.fct_orders
[2022-02-15 03:25:22,064] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.test.my_new_project.fct_orders manual__2022-02-15T03:24:14.594120+00:00 [running]> on host 459d09dd7c86
[2022-02-15 03:25:22,190] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=test.my_new_project.fct_orders
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T03:24:14.594120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T03:24:14.594120+00:00
[2022-02-15 03:25:22,193] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 03:25:22,195] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json test --target dev --models fct_orders             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 03:25:22,213] {subprocess.py:85} INFO - Output:
[2022-02-15 03:25:29,242] {subprocess.py:89} INFO - 03:25:29  Running with dbt=1.0.1
[2022-02-15 03:25:29,677] {subprocess.py:89} INFO - 03:25:29  Found 8 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 03:25:29,686] {subprocess.py:89} INFO - 03:25:29
[2022-02-15 03:25:29,688] {subprocess.py:89} INFO - 03:25:29  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-02-15 03:25:30,174] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 03:25:30,211] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=test.my_new_project.fct_orders, execution_date=20220215T032414, start_date=20220215T032521, end_date=20220215T032530
[2022-02-15 03:25:30,272] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 03:25:30,314] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
