[2022-02-15 03:25:21,923] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.dim_customers manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:21,952] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.model.my_new_project.dim_customers manual__2022-02-15T03:24:14.594120+00:00 [queued]>
[2022-02-15 03:25:21,954] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:21,955] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 03:25:21,957] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 03:25:21,979] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): model.my_new_project.dim_customers> on 2022-02-15 03:24:14.594120+00:00
[2022-02-15 03:25:21,987] {standard_task_runner.py:52} INFO - Started process 2220 to run task
[2022-02-15 03:25:21,999] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'model.my_new_project.dim_customers', 'manual__2022-02-15T03:24:14.594120+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmpionymcq9', '--error-file', '/tmp/tmpg0_3edaf']
[2022-02-15 03:25:22,001] {standard_task_runner.py:77} INFO - Job 135: Subtask model.my_new_project.dim_customers
[2022-02-15 03:25:22,126] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.model.my_new_project.dim_customers manual__2022-02-15T03:24:14.594120+00:00 [running]> on host 459d09dd7c86
[2022-02-15 03:25:22,282] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=model.my_new_project.dim_customers
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T03:24:14.594120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T03:24:14.594120+00:00
[2022-02-15 03:25:22,285] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 03:25:22,294] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json run --target dev --models dim_customers             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 03:25:22,355] {subprocess.py:85} INFO - Output:
[2022-02-15 03:25:29,442] {subprocess.py:89} INFO - 03:25:29  Running with dbt=1.0.1
[2022-02-15 03:25:29,884] {subprocess.py:89} INFO - 03:25:29  Found 8 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 03:25:29,892] {subprocess.py:89} INFO - 03:25:29
[2022-02-15 03:25:33,141] {subprocess.py:89} INFO - 03:25:33  Concurrency: 4 threads (target='dev')
[2022-02-15 03:25:33,144] {subprocess.py:89} INFO - 03:25:33
[2022-02-15 03:25:33,168] {subprocess.py:89} INFO - 03:25:33  1 of 1 START table model dbt_bytecode_training.dim_customers.................... [RUN]
[2022-02-15 03:25:36,422] {subprocess.py:89} INFO - 03:25:36  1 of 1 OK created table model dbt_bytecode_training.dim_customers............... [SUCCESS 1 in 3.25s]
[2022-02-15 03:25:36,501] {subprocess.py:89} INFO - 03:25:36
[2022-02-15 03:25:36,503] {subprocess.py:89} INFO - 03:25:36  Finished running 1 table model in 6.61s.
[2022-02-15 03:25:36,508] {subprocess.py:89} INFO - 03:25:36
[2022-02-15 03:25:36,510] {subprocess.py:89} INFO - 03:25:36  Completed successfully
[2022-02-15 03:25:36,512] {subprocess.py:89} INFO - 03:25:36
[2022-02-15 03:25:36,514] {subprocess.py:89} INFO - 03:25:36  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-02-15 03:25:36,920] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 03:25:36,952] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=model.my_new_project.dim_customers, execution_date=20220215T032414, start_date=20220215T032521, end_date=20220215T032536
[2022-02-15 03:25:36,987] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 03:25:37,034] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
